import Head from 'next/head'
import GridListWithHeading from '@/components/list'
import StatsTitleDescription from '@/components/stats'

export default function Features() {
  return (
    <>
      <Head>
        <title>Features | Next MF app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <StatsTitleDescription />
        <GridListWithHeading />
      </main>
    </>
  )
}
