import Head from 'next/head'

import dynamic from 'next/dynamic';

const Hero = dynamic(
  () => import('content/Hero').then((mod) => mod.Hero),
  {
    ssr: true,
  }
);

const Search = dynamic(
  () => import('shop/Search').then((mod) => mod.Search),
  {
    ssr: true,
  }
);

const Featured = dynamic(
  () => import('shop/Featured').then((mod) => mod.Featured),
  {
    ssr: true,
  }
);

export function Home({ heroProps, featuredProps }) {
  return (
    <>
      <Head>
        <title>Next MF app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero {...heroProps} />
        <Search />
        <Featured {...featuredProps} />
      </main>
    </>
  )
}

export const getServerSideProps = async (ctx) => {
  const [hero, featured] = await Promise.all([
    import('content/Hero'),
    import('shop/Featured'),
  ]);

  if (hero.getServerSideProps && featured.getServerSideProps) {
    const [heroProps, featuredProps] = await Promise.all([
      hero.getServerSideProps(ctx),
      featured.getServerSideProps(ctx),
    ]);
    return {
      props: {
        heroProps: heroProps.props,
        featuredProps: featuredProps.props,
      }
    }
  }

  return {
    props: {},
  }
}

export default Home;
