import Head from 'next/head'
import ThreeTierPricing from '@/components/pricing'

export function Pricing() {
  return (
    <>
      <Head>
        <title>Pricing | Next MF app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThreeTierPricing />
      </main>
    </>
  )
}

export async function getServerSideProps({ query }) {
  return {
    props: {},
  };
}

export default Pricing
