import Head from 'next/head'
import ThreeTierPricing from '@/components/pricing'

export function Pricing({ name }) {
  return (
    <>
      <Head>
        <title>Pricing | Next MF app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ThreeTierPricing />
        {JSON.stringify({ name })}
      </main>
    </>
  )
}

export async function getServerSideProps({ query }) {
  const res = await fetch('https://pokeapi.co/api/v2/pokemon/' + (Date.now()%100));
  const pokemon = await res.json();

  return {
    props: {
      name: pokemon.name,
    },
  };
}

export default Pricing
